apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: task-service-ingress
spec:
  rules:
    - host: example.com   # use your domain or omit for some local setups
      http:
        paths:
          - path: /tasks
            pathType: Prefix
            backend:
              service:
                name: task-service
                port:
                  number: 80
